### ISSUE TITLE
Error on settings locks app

### ISSUE THREAD

**Issue by chadkoh** [fission-codes/everywhere-computer-control-panel#17]
Reproduction:

1. Open the ECCP
2. Navigate to Settings
3. Click on any other navmenu item. You will not be able to leave Settings page even though the URL updates

Console shows the following error:

```
Uncaught (in promise) TypeError: r[0].nodeInfo.static is undefined
    de NodeInfo.svelte:41
    p NodeInfo.svelte:36
    Kt index.mjs:1347
    wt index.mjs:1307
[NodeInfo.svelte:41:9](http://localhost:4173/src/components/settings/NodeInfo.svelte)
```

**Comment by avivash** [comment]
This is working on `main`

**Comment by avivash** [comment]
re-opening in case it's tied to a different method of install homestar or something like that. i'll do some testing to see if i can reproduce it that way

**Comment by avivash** [comment]
@hugomrdias it looks like this happens if you use the `homestar-runtime` package because it's not pulling the latest backend code. the shape of the response from the `health` endpoint changed in the latest backend code 👍🏼

**Comment by avivash** [comment]
old shape:
<img width="503" alt="image" src="https://github.com/fission-codes/everywhere-computer-control-panel/assets/1179291/cb9c0980-fc19-4f45-95bb-27c51136edf9">

new shape:
<img width="575" alt="image" src="https://github.com/fission-codes/everywhere-computer-control-panel/assets/1179291/01d9d5a6-6e61-4167-a17e-284b5b59a345">

**Comment by hugomrdias** [comment]
The client and runtime 📦 s has been updated

Hugo Dias
